# from - путь к файлу, который необходимо скопировать
# to - папка назначения
# pause - период копирования в минутах (десятичный разделитель .)
# необходимо указывать два слеша перед директорией
# приложение будет копировать все файлы находящиеся в директории

from: C:\\Users\\muv\\XLSX-copy-parser\\from\\
to: C:\\Users\\muv\\XLSX-copy-parser\\to
pause: 5